/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wingman.clothingshopmanagement.view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import lombok.Getter;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Getter for the loading label component.
     *
     * @return the loading label component
     */
    @Getter
    private JLabel loadingLabel;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        setResizable(false);
        setTitle("Clothing Shop Management");
        setLocation(500, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Adds a loading GIF to the center of the window.
     */
    public final void addLoadingGif() {
        ImageIcon loadingGif = new ImageIcon(getClass().getResource("/gifs/loading.gif"));
        loadingLabel = new JLabel(loadingGif);
        int labelWidth = loadingLabel.getPreferredSize().width;
        int labelHeight = loadingLabel.getPreferredSize().height;

        int x = (getWidth() - labelWidth) / 2;
        int y = (getHeight() - labelHeight) / 2;

        loadingLabel.setBounds(x, y, labelWidth, labelHeight);
        add(loadingLabel);
        loadingLabel.setVisible(false);
    }

    /**
     * Removes the loading GIF from the window.
     */
    public final void removeLoadingGif() {
        remove(loadingLabel);
    }

    /**
     * Displays the loading GIF.
     */
    public void showLoading() {
        loadingLabel.setVisible(true);
    }

    /**
     * Hides the loading GIF.
     */
    public void hideLoading() {
        loadingLabel.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
