/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wingman.clothingshopmanagement.view.panel.message;

import com.wingman.clothingshopmanagement.view.components.CustomPanel;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author Administrator
 */
public class ConfirmPanel extends CustomPanel {

    private final Runnable confirmTask;

    /**
     * Creates new form InfoMessagePanel
     * @param message
     * @param confirmTask
     */
    public ConfirmPanel(String message, Runnable confirmTask) {
        initComponents();
         content.setText(String.format("<html><p style='text-align: center; width: 190px;'>%s</p></html>", message));
        this.confirmTask = confirmTask;
    }
    
    public static void show(String mesage, Runnable confirmTask) {
        GlassPanePopup.showPopup(new ConfirmPanel(mesage, confirmTask), "confirm");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JLabel();
        cancelBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        yesBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorderColor(java.awt.Color.lightGray);
        setRadius(16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(87, 87, 87));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Are you sure?");
        jLabel1.setFocusable(false);

        content.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        content.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        content.setText("<html><p style='text-align: center; width: 160px;'>Đây là nội dung của JLabel.</p></html>");

        cancelBtn.setBackground(new java.awt.Color(193, 193, 193));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("CANCEL");
        cancelBtn.setBorderColor(new java.awt.Color(193, 193, 193));
        cancelBtn.setColor(new java.awt.Color(193, 193, 193));
        cancelBtn.setColorClick(new java.awt.Color(142, 142, 142));
        cancelBtn.setColorOver(new java.awt.Color(142, 142, 142));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBtn.setRadius(16);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        yesBtn.setBackground(new java.awt.Color(223, 107, 81));
        yesBtn.setForeground(new java.awt.Color(255, 255, 255));
        yesBtn.setText("YES");
        yesBtn.setBorderColor(new java.awt.Color(223, 107, 81));
        yesBtn.setColor(new java.awt.Color(223, 107, 81));
        yesBtn.setColorClick(new java.awt.Color(187, 50, 59));
        yesBtn.setColorOver(new java.awt.Color(187, 50, 59));
        yesBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yesBtn.setRadius(16);
        yesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2)
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        GlassPanePopup.closePopup("confirm");
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        GlassPanePopup.closePopup("confirm");
        confirmTask.run();
    }//GEN-LAST:event_yesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wingman.clothingshopmanagement.view.components.CustomButton cancelBtn;
    private javax.swing.JLabel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.wingman.clothingshopmanagement.view.components.CustomButton yesBtn;
    // End of variables declaration//GEN-END:variables
}
