/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wingman.clothingshopmanagement.view.panel;

import com.wingman.clothingshopmanagement.model.user.Permission;
import com.wingman.clothingshopmanagement.model.user.User;
import com.wingman.clothingshopmanagement.view.MainFrame;
import com.wingman.clothingshopmanagement.view.components.CustomButton;
import com.wingman.clothingshopmanagement.view.panel.home.HomePanel;
import com.wingman.clothingshopmanagement.view.panel.order.OrderManagementPanel;
import com.wingman.clothingshopmanagement.view.panel.order.OrderPanel;
import com.wingman.clothingshopmanagement.view.panel.product.ProductManagementPanel;
import com.wingman.clothingshopmanagement.view.panel.revenue.RevenuePanel;
import com.wingman.clothingshopmanagement.view.panel.user.UserInfoPanel;
import com.wingman.clothingshopmanagement.view.panel.user.UserManagementPanel;
import java.awt.Color;
import javax.swing.JPanel;
import lombok.Getter;


@Getter
public class DashboardPanel extends javax.swing.JLayeredPane {
    private JPanel contentPanel;
    private final User user;
    /**
     * Creates new form Temp
     * @param user
     */
    public DashboardPanel(User user) {
        initComponents();
        this.user = user;
        homeBtn.doClick();
        
        if (!user.getPermission().equals(Permission.ADMINISTRATOR)) {
            manageUserBtn.setEnabled(false);
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userInfoBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        customPanel1 = new com.wingman.clothingshopmanagement.view.components.CustomPanel();
        homeBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        manageUserBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        manageProductBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        orderBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        manageOrderBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        revenueBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        logoutBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 243, 243));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(125, 44, 224));
        jLabel1.setText("Clothing Shop Management");

        userInfoBtn.setBackground(new java.awt.Color(125, 44, 224));
        userInfoBtn.setBorder(null);
        userInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        userInfoBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        userInfoBtn.setColor(new java.awt.Color(125, 44, 224));
        userInfoBtn.setColorClick(new java.awt.Color(125, 44, 224));
        userInfoBtn.setColorOver(new java.awt.Color(125, 44, 224));
        userInfoBtn.setPreferredSize(new java.awt.Dimension(36, 36));
        userInfoBtn.setRadius(100);
        userInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 956, Short.MAX_VALUE)
                .addComponent(userInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        customPanel1.setBackground(new java.awt.Color(125, 44, 224));
        customPanel1.setBorderColor(new java.awt.Color(244, 243, 243));
        customPanel1.setColor(new java.awt.Color(125, 44, 224));
        customPanel1.setPreferredSize(new java.awt.Dimension(249, 686));
        customPanel1.setRadius(16);

        homeBtn.setBackground(new java.awt.Color(125, 44, 224));
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setActionCommand("  Home");
        homeBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        homeBtn.setColor(new java.awt.Color(125, 44, 224));
        homeBtn.setColorClick(new java.awt.Color(75, 3, 163));
        homeBtn.setColorOver(new java.awt.Color(96, 33, 173));
        homeBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeBtn.setIconTextGap(12);
        homeBtn.setPreferredSize(new java.awt.Dimension(112, 44));
        homeBtn.setRadius(10);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        manageUserBtn.setBackground(new java.awt.Color(125, 44, 224));
        manageUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        manageUserBtn.setText("Manage Users");
        manageUserBtn.setActionCommand("  Home");
        manageUserBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        manageUserBtn.setColor(new java.awt.Color(125, 44, 224));
        manageUserBtn.setColorClick(new java.awt.Color(75, 3, 163));
        manageUserBtn.setColorOver(new java.awt.Color(96, 33, 173));
        manageUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageUserBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageUserBtn.setIconTextGap(12);
        manageUserBtn.setPreferredSize(new java.awt.Dimension(112, 44));
        manageUserBtn.setRadius(10);
        manageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserBtnActionPerformed(evt);
            }
        });

        manageProductBtn.setBackground(new java.awt.Color(125, 44, 224));
        manageProductBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clothes-hanger.png"))); // NOI18N
        manageProductBtn.setText("Manage Products");
        manageProductBtn.setActionCommand("  Home");
        manageProductBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        manageProductBtn.setColor(new java.awt.Color(125, 44, 224));
        manageProductBtn.setColorClick(new java.awt.Color(75, 3, 163));
        manageProductBtn.setColorOver(new java.awt.Color(96, 33, 173));
        manageProductBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageProductBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageProductBtn.setIconTextGap(12);
        manageProductBtn.setPreferredSize(new java.awt.Dimension(112, 44));
        manageProductBtn.setRadius(10);
        manageProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductBtnActionPerformed(evt);
            }
        });

        orderBtn.setBackground(new java.awt.Color(125, 44, 224));
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart.png"))); // NOI18N
        orderBtn.setText("Order");
        orderBtn.setActionCommand("  Home");
        orderBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        orderBtn.setColor(new java.awt.Color(125, 44, 224));
        orderBtn.setColorClick(new java.awt.Color(75, 3, 163));
        orderBtn.setColorOver(new java.awt.Color(96, 33, 173));
        orderBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        orderBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        orderBtn.setIconTextGap(12);
        orderBtn.setPreferredSize(new java.awt.Dimension(112, 44));
        orderBtn.setRadius(10);
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        manageOrderBtn.setBackground(new java.awt.Color(125, 44, 224));
        manageOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard.png"))); // NOI18N
        manageOrderBtn.setText("Manage Orders");
        manageOrderBtn.setActionCommand("  Home");
        manageOrderBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        manageOrderBtn.setColor(new java.awt.Color(125, 44, 224));
        manageOrderBtn.setColorClick(new java.awt.Color(75, 3, 163));
        manageOrderBtn.setColorOver(new java.awt.Color(96, 33, 173));
        manageOrderBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageOrderBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageOrderBtn.setIconTextGap(12);
        manageOrderBtn.setPreferredSize(new java.awt.Dimension(112, 44));
        manageOrderBtn.setRadius(10);
        manageOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderBtnActionPerformed(evt);
            }
        });

        revenueBtn.setBackground(new java.awt.Color(125, 44, 224));
        revenueBtn.setForeground(new java.awt.Color(255, 255, 255));
        revenueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money-tag.png"))); // NOI18N
        revenueBtn.setText("Revenue");
        revenueBtn.setActionCommand("  Home");
        revenueBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        revenueBtn.setColor(new java.awt.Color(125, 44, 224));
        revenueBtn.setColorClick(new java.awt.Color(75, 3, 163));
        revenueBtn.setColorOver(new java.awt.Color(96, 33, 173));
        revenueBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        revenueBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        revenueBtn.setIconTextGap(12);
        revenueBtn.setPreferredSize(new java.awt.Dimension(112, 44));
        revenueBtn.setRadius(10);
        revenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(125, 44, 224));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutBtn.setText("Log out");
        logoutBtn.setActionCommand("  Home");
        logoutBtn.setAlignmentY(0.0F);
        logoutBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        logoutBtn.setColor(new java.awt.Color(125, 44, 224));
        logoutBtn.setColorClick(new java.awt.Color(75, 3, 163));
        logoutBtn.setColorOver(new java.awt.Color(96, 33, 173));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutBtn.setIconTextGap(12);
        logoutBtn.setPreferredSize(new java.awt.Dimension(112, 44));
        logoutBtn.setRadius(10);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(manageProductBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(revenueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revenueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(customPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfoBtnActionPerformed
        UserInfoPanel panel = new UserInfoPanel(user);
        panel.display();
    }//GEN-LAST:event_userInfoBtnActionPerformed

    private void revenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueBtnActionPerformed
        resetButtonBackgroundColor();
        setButtonBackgroundColor(revenueBtn, new Color(96, 33, 173));
        setConentPanel(new RevenuePanel());
    }//GEN-LAST:event_revenueBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        MainFrame.getInstance().showLoginPanel();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        resetButtonBackgroundColor();
        setButtonBackgroundColor(homeBtn, new Color(96, 33, 173));
        setConentPanel(new HomePanel());
    }//GEN-LAST:event_homeBtnActionPerformed

    private void manageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserBtnActionPerformed
        resetButtonBackgroundColor();
        setButtonBackgroundColor(manageUserBtn, new Color(96, 33, 173));
        setConentPanel(new UserManagementPanel());
    }//GEN-LAST:event_manageUserBtnActionPerformed

    private void manageProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductBtnActionPerformed
        resetButtonBackgroundColor();
        setButtonBackgroundColor(manageProductBtn, new Color(96, 33, 173));
        setConentPanel(new ProductManagementPanel());
    }//GEN-LAST:event_manageProductBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        resetButtonBackgroundColor();
        setButtonBackgroundColor(orderBtn, new Color(96, 33, 173));
        setConentPanel(new OrderPanel());
    }//GEN-LAST:event_orderBtnActionPerformed

    private void manageOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderBtnActionPerformed
        resetButtonBackgroundColor();
        setButtonBackgroundColor(manageOrderBtn, new Color(96, 33, 173));
        setConentPanel(new OrderManagementPanel());
    }//GEN-LAST:event_manageOrderBtnActionPerformed
    
    public void setConentPanel(JPanel panel) {
        if (contentPanel != null) {
            remove(contentPanel);
        }
        contentPanel = panel;
        add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 55, 1006, 684));
        revalidate();
    }
    
    private void resetButtonBackgroundColor() {
        setButtonBackgroundColor(homeBtn, new Color(125, 44, 224));
        setButtonBackgroundColor(manageUserBtn, new Color(125, 44, 224));
        setButtonBackgroundColor(manageProductBtn, new Color(125, 44, 224));
        setButtonBackgroundColor(orderBtn, new Color(125, 44, 224));
        setButtonBackgroundColor(manageOrderBtn, new Color(125, 44, 224));
        setButtonBackgroundColor(revenueBtn, new Color(125, 44, 224));
    }
    private void setButtonBackgroundColor(CustomButton button, Color color) {
        button.setBackground(color);
        button.setColor(color);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wingman.clothingshopmanagement.view.components.CustomPanel customPanel1;
    private com.wingman.clothingshopmanagement.view.components.CustomButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private com.wingman.clothingshopmanagement.view.components.CustomButton logoutBtn;
    private com.wingman.clothingshopmanagement.view.components.CustomButton manageOrderBtn;
    private com.wingman.clothingshopmanagement.view.components.CustomButton manageProductBtn;
    private com.wingman.clothingshopmanagement.view.components.CustomButton manageUserBtn;
    private com.wingman.clothingshopmanagement.view.components.CustomButton orderBtn;
    private com.wingman.clothingshopmanagement.view.components.CustomButton revenueBtn;
    private com.wingman.clothingshopmanagement.view.components.CustomButton userInfoBtn;
    // End of variables declaration//GEN-END:variables
}
