/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wingman.clothingshopmanagement.view.panel;

import com.wingman.clothingshopmanagement.model.dao.DAOManager;
import com.wingman.clothingshopmanagement.model.dao.UserDAO;
import com.wingman.clothingshopmanagement.util.BCryptUtil;
import com.wingman.clothingshopmanagement.util.ImageUtil;
import com.wingman.clothingshopmanagement.view.MainFrame;
import com.wingman.clothingshopmanagement.view.panel.message.WarningPanel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;


public class LoginPanel extends javax.swing.JPanel {
    private static final String EMAIL_PATTERN = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        forgotPasswordBtn.setVisible(false);
        shopImageLabel.setIcon(ImageUtil.resize(new ImageIcon(getClass().getResource("/images/shop.png")), 565, 756));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopImageLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailTextField = new com.wingman.clothingshopmanagement.view.components.CustomTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new com.wingman.clothingshopmanagement.view.components.CustomPasswordField();
        forgotPasswordBtn = new javax.swing.JButton();
        loginBtn = new com.wingman.clothingshopmanagement.view.components.CustomButton();

        setBackground(new java.awt.Color(255, 255, 255));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(125, 44, 224));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Email");

        emailTextField.setBoderColor(java.awt.Color.lightGray);
        emailTextField.setHint("Enter email");
        emailTextField.setRadius(16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        passwordField.setToolTipText("");
        passwordField.setBorderColor(java.awt.Color.lightGray);
        passwordField.setHint("Enter password");
        passwordField.setHintColor(new java.awt.Color(128, 128, 128));
        passwordField.setRadius(16);
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });

        forgotPasswordBtn.setText("Forgot password?");
        forgotPasswordBtn.setBorder(null);
        forgotPasswordBtn.setContentAreaFilled(false);
        forgotPasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        forgotPasswordBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        forgotPasswordBtn.setIconTextGap(0);

        loginBtn.setBackground(new java.awt.Color(125, 44, 224));
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setBorderColor(new java.awt.Color(125, 44, 224));
        loginBtn.setColor(new java.awt.Color(125, 44, 224));
        loginBtn.setColorClick(new java.awt.Color(75, 3, 163));
        loginBtn.setColorOver(new java.awt.Color(96, 33, 173));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setIconTextGap(12);
        loginBtn.setPreferredSize(new java.awt.Dimension(118, 36));
        loginBtn.setRadius(16);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(shopImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                                    .addComponent(forgotPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shopImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotPasswordBtn)
                .addGap(43, 43, 43)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        handleLogin();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginBtn.doClick();
        }
    }//GEN-LAST:event_passwordFieldKeyReleased
    
    private void handleLogin() {
        emailTextField.setBoderColor(Color.GRAY);
        passwordField.setBorderColor(Color.GRAY);
        
        String email = emailTextField.getText();
        String password = new String(passwordField.getPassword());
        
        if (email.isBlank()) {
            emailTextField.setBoderColor(Color.RED);
            SwingUtilities.updateComponentTreeUI(this);
            WarningPanel.show("Email is empty!");
            return;
        }
        
        if (password.isBlank()) {
            passwordField.setBorderColor(Color.RED);
            SwingUtilities.updateComponentTreeUI(this);
            WarningPanel.show("Password is empty!");
            return;
        }
        
        if (!validateEmail(emailTextField.getText())) {
            emailTextField.setBoderColor(Color.RED);
            SwingUtilities.updateComponentTreeUI(this);
            WarningPanel.show("Email is not valid!");
            return;
        }
        
        UserDAO userDAO = DAOManager.getInstance().getUserDAO();
        MainFrame.getInstance().getLoading().showLoading();
        userDAO.get(emailTextField.getText()).thenAccept((user) -> {
            if (user == null) {
                MainFrame.getInstance().getLoading().hideLoading();
                WarningPanel.show("User does not exist!");
                return;
            }
            if (!BCryptUtil.check(password, user.getHashedPassword())) {
                MainFrame.getInstance().getLoading().hideLoading();
                WarningPanel.show("Wrong password!");
                return;
            }
            
            user.setLastActive(new Date());
            userDAO.update(user).join();
            
            MainFrame.getInstance().getLoading().hideLoading();
            MainFrame.getInstance().showDashboardPanel(user);
        }).whenComplete((t, u) -> {
            MainFrame.getInstance().getLoading().hideLoading();
            if (u != null) {
                u.printStackTrace();
                throw new RuntimeException(u);
            }
        });
    }
    
    private boolean validateEmail(String email) {
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wingman.clothingshopmanagement.view.components.CustomTextField emailTextField;
    private javax.swing.JButton forgotPasswordBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.wingman.clothingshopmanagement.view.components.CustomButton loginBtn;
    private javax.swing.JLabel loginLabel;
    private com.wingman.clothingshopmanagement.view.components.CustomPasswordField passwordField;
    private javax.swing.JLabel shopImageLabel;
    // End of variables declaration//GEN-END:variables
}
