/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wingman.clothingshopmanagement.view.panel;

/**
 *
 * @author Administrator
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customButton1 = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        customButton7 = new com.wingman.clothingshopmanagement.view.components.CustomButton();
        customButton9 = new com.wingman.clothingshopmanagement.view.components.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customButton1.setBackground(new java.awt.Color(125, 44, 224));
        customButton1.setForeground(new java.awt.Color(255, 255, 255));
        customButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        customButton1.setText("Home");
        customButton1.setActionCommand("  Home");
        customButton1.setBorderColor(new java.awt.Color(125, 44, 224));
        customButton1.setColor(new java.awt.Color(125, 44, 224));
        customButton1.setColorClick(new java.awt.Color(75, 3, 163));
        customButton1.setColorOver(new java.awt.Color(75, 3, 163));
        customButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customButton1.setIconTextGap(12);
        customButton1.setPreferredSize(new java.awt.Dimension(112, 44));
        customButton1.setRadius(10);

        customButton7.setBackground(new java.awt.Color(125, 44, 224));
        customButton7.setForeground(new java.awt.Color(255, 255, 255));
        customButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money-tag.png"))); // NOI18N
        customButton7.setText("Revenue");
        customButton7.setActionCommand("  Home");
        customButton7.setBorderColor(new java.awt.Color(125, 44, 224));
        customButton7.setColor(new java.awt.Color(125, 44, 224));
        customButton7.setColorClick(new java.awt.Color(75, 3, 163));
        customButton7.setColorOver(new java.awt.Color(75, 3, 163));
        customButton7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customButton7.setIconTextGap(12);
        customButton7.setPreferredSize(new java.awt.Dimension(112, 44));
        customButton7.setRadius(10);
        customButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton7ActionPerformed(evt);
            }
        });

        customButton9.setBackground(new java.awt.Color(125, 44, 224));
        customButton9.setForeground(new java.awt.Color(255, 255, 255));
        customButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        customButton9.setText("Log out");
        customButton9.setActionCommand("  Home");
        customButton9.setBorderColor(new java.awt.Color(125, 44, 224));
        customButton9.setColor(new java.awt.Color(125, 44, 224));
        customButton9.setColorClick(new java.awt.Color(75, 3, 163));
        customButton9.setColorOver(new java.awt.Color(75, 3, 163));
        customButton9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        customButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customButton9.setIconTextGap(12);
        customButton9.setPreferredSize(new java.awt.Dimension(112, 44));
        customButton9.setRadius(10);
        customButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(customButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(customButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(customButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(82, 82, 82)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton7ActionPerformed

    }//GEN-LAST:event_customButton7ActionPerformed

    private void customButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton9ActionPerformed

    }//GEN-LAST:event_customButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wingman.clothingshopmanagement.view.components.CustomButton customButton1;
    private com.wingman.clothingshopmanagement.view.components.CustomButton customButton7;
    private com.wingman.clothingshopmanagement.view.components.CustomButton customButton9;
    // End of variables declaration//GEN-END:variables
}
